# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)\
puts "Creating brand 🍷"
Brand.create(name:"Robert Mondavi" , description:"Robert Mondavi established his namesake winery in 1966 with a vision to create Napa Valley wines that would stand in the company of the world’s finest. He chose To Kalon Vineyard in the heart of Napa Valley as the home for Robert Mondavi Winery. This first-growth vineyard, located in Oakville, California, is renowned for producing some of the finest Cabernet Sauvignon wines in the world, as well as for its Sauvignon Blanc grapes, from which Mr. Mondavi crafted his signature wine, Fumé Blanc." , est:1966  )
Brand.create(name:"14 Hands" , description:"14 Hands is inspired by the unbridled spirit of the wild horses that once freely roamed eastern Washington and the Columbia River Valley." , est:2005  )
Brand.create(name:"Santa Margherita" , description:"Grown, harvested, and produced in Italy, our wines are rooted in classic Italian ideals and reimagined for the fine wine lover of today. We invite you to discover the heart and soul of Santa Margherita, our people, passion, and commitment to producing authentic, sustainable, deliciously enjoyable wines for the life you live." , est:1935  )

puts "Creating Location 🍷"
Location.create(country:"United States Of America" , state:"California" , city:"Napa Valley")
Location.create(country:"United States Of America" , state:"Washington" , city:"Prosser")
Location.create(country:"Italy" , state:"Veneto region" , city:"none")


puts "Creating Wine 🍷"
Wine.create(name:"2019 Cabernet Sauvignon Napa Valley" , vintage:2019, blend:"80% Cabernet Sauvignon 11% Merlot 5% Petit Verdot3% Cabernet Franc 1% Malbec" , flavor_profile:"CherryPurple Plum Sage Sandalwood Mint Vanilla Bean" , description:"Framed by lovey bright acidity and fine tannins, the 2019 Cabernet Sauvignon has vibrant fruit notes shining through to the end.", img_url:"https://images.vivino.com/thumbs/VILxV-cZS6y7rweBrgY2sQ_pb_x600.png",  location_id:1 , brand_id:1)
Wine.create(name:"2019 Moscato d'Oro Napa Valley" , vintage:2019, blend:"100% Muscat" , flavor_profile:"Vibrant Lime Blossom Honeysuckle Crushed Pineapple" , description:"Vibrant lime blossom, honeysuckle and crushed pineapple on the nose meet juicy white peach, candied fennel and bright, zesty clementine on the palate.", img_url:"https://cdn.shopify.com/s/files1/0540/2686/2769/products/2019Moscatod_OroNapaValley375THUMB500x500.jpg?v=1668627766",  location_id:1 , brand_id:1)
Wine.create(name:"2021 Sparkling Rosé Napa Valley" , vintage:2021, blend:"76% Muscat 13% Malbec 11% Pinot Noir" , flavor_profile:"Rose Orange Blossom Peach Hints of Sweet Red Berries" , description:"Our Sparkling Rosé is made from predominately Moscato di Canelli grapes from our Wappo Hill Vineyard in Stags Leap. We blended in a small percentage of rosé wine made from Malbec grapes from our To Kalon Vineyard and Pinot Noir grapes from Stanly Ranch in Carneros. A true Napa Valley blend.", img_url:"https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSUrWlNIXgeHi3k6_ccFUOhbF7Oxzbz95cHuuei7r6X9VgLfV9_",  location_id:1 , brand_id:1)

Wine.create(name:"2021 Chardonnay " , vintage:2021, blend:"95% Chardonnay & 5% other select varieties" , flavor_profile:"melon, apple, pear" , description:"This lighter style Chardonnay begins with delicate floral aromas complemented by rich melon, apple and pear flavors", img_url:"https://images-us-prod.cms.commerce.dynamics.com/cms/api/mhtmhnbtbn/imageFileData/search?fileName=/Products%2F70393_000_001.png&w=0&h=600&q=80&m=6&f=png",  location_id: 2 , brand_id: 2)
Wine.create(name:"2020 “Hot to Trot” Smooth Red Wine Blend " , vintage:2020, blend:"57% Merlot, 25% Syrah, 13.5% Cabernet Sauvignon & 5% other select varieties" , flavor_profile:"cherry pie, ripe berries and plums, supported by a frame of refined tannins, give way to subtle notes of baking spice on a persistent finish." , description:"This polished red wine offers aromas of cherry, red currant and tea. Flavors of cherry pie, ripe berries and plums, supported by a frame of refined tannins, give way to subtle notes of baking spice on a persistent finish.",img_url:"https://images-us-prod.cms.commerce.dynamics.com/cms/api/mhtmhnbtbn/imageFileData/search?fileName=/Products%2F71122_000_001.png&w=0&h=600&q=80&m=6&f=png" , location_id: 2 , brand_id: 2)
Wine.create(name:"Unicorn Rosé Bubbles" , vintage:0000, blend:"57% Merlot, 25% Syrah, 13.5% Cabernet Sauvignon & 5% other select varieties" , flavor_profile:"This light, fresh Rosé Wine starts with elegant scents of cranberry, pomegranate and Bing cherry. Delicate red fruit flavors are joined by a pleasant effervescence and a juicy crispness that lead to a refreshing finish." , description:"Perfect for an afternoon picnic, an evening of sunset gazing, a night of binge watching your favorite series or any other occasion where fun is about to happen with family and friends.", img_url:"https://images-us-prod.cms.commerce.dynamics.com/cms/api/mhtmhnbtbn/imageFileData/search?fileName=/Products%2F71321_000_001.png&w=0&h=600&q=80&m=6&f=png",  location_id: 2 , brand_id: 2)

Wine.create(name:"PINOT GRIGIO" , vintage:0000, blend:"Pinot Grigio" , flavor_profile:"Delicate fruit and floral notes, aroma of Golden Delicious apples." , description:"Straw-yellow in color with a bright, well-balanced taste. Perfect for a light before-dinner glass of wine.", img_url:"https://santamargheritawines.com/wp-content/uploads/2020/07/Pinot-Grigio-Valdadige-750ml.jpg", location_id: 3 , brand_id: 3)
Wine.create(name:"Chianti Classico" , vintage:0000, blend:"Sangiovese (90%), Merlot (5%) and Cabernet Sauvignon (5%)" , flavor_profile:"The aromas of this complex red wine range from cherries and plums to gladiolus flowers and earthy flint. The tannic, oak-aged flavors are bright and round, with a dry, warm, fresh earthy finish." , description:"Our Chianti Classico Riserva gets its name and its unmistakable spirit from its birthplace in the heart of Tuscany. Rooted in history – the Romans cultivated grapes in the region over 700 years ago – this classic wine has had a long and aristocratic history throughout the world.", img_url:"https://santamargheritawines.com/wp-content/uploads/2020/07/chianti-classico1.jpg", location_id: 3 , brand_id: 3)
Wine.create(name:"PROSECCO SUPERIORE DI VALDOBBIADENE D.O.C.G." , vintage:0000, blend:"Glera" , flavor_profile:"This sparkling wine has fine, lively bubbles that dance within its bright straw-yellow color and greenish reflections. Its lovely aromas include ripe pineapples, peaches, and Rennet apples as well as delicate florals. Its finish is bright and dry, yet sweet on the palate." , description:"This bubbly favorite creates a celebration whenever it is enjoyed and is the ideal accompaniment to a lively dinner. Its aroma, freshness, and vibrancy make it a treasure that you will want to share again and again. Prosecco Superiore makes any gathering a memorable occasion.", img_url:"https://santamargheritawines.com/wp-content/uploads/2020/07/prosecco-superiore1.jpg" , location_id: 3 , brand_id: 3)
puts "Wines Ready 🍷 "
